### ISSUE TITLE
Tool used for authoring dansuma HLA?

### ISSUE THREAD

**Issue by gmacario** [kuruho/dansuma#2]
@lucabelluccini A few questions:

* [x] Q1: Which tool/version did you use for authoring https://github.com/kuruho/dansuma/blob/master/Hackaton_HLA.svg ?
  - A: Google Drive
   - Q: ??? Do you mean "Google Docs", "Google Sheets", "Google Slides" or what?
* [x] Q2: It looks like `*.svg` are not rendered quite beautifully in GitHub. Could you also export the diagram in `*.png` please? Where are you trying to integrate it?
  - A: Use this link: <https://cdn.rawgit.com/kuruho/dansuma/2b6d79a4/Hackaton_HLA.svg>
* [x] Q3: Is `*.svg` the native format of such a tool? If not, could you also upload the native format of the HLA?
   - A:  I do not think it is. It is partially vectorial and the rest is the existing volumio diagram.

**Comment by gmacario** [comment]
@lucabelluccini  I did not notice your answers (directly inlined to my questions), also GitHub does not help as AFAIK there is no history when editing single comments.

Anyway I have done some markdown adjustments so that should be more clear now.
IMHO Q1 is still open, though

**Comment by lucabelluccini** [comment]
I used Google Drive / Draw (but I know there are online tools far more powerful than it (I actually hate google draw but ...).

Link to the [original](https://docs.google.com/drawings/d/1HqPeF5K9ZnQ7A_6KMyGlpmV7hnP5FZ4zTa3Yp2SrgRc/edit?usp=sharing)

- https://www.draw.io/
- https://cacoo.com/
- https://www.gliffy.com/
- https://www.lucidchart.com
- http://www.plantuml.com/plantuml/uml/ (PlantUML syntax)
- https://www.websequencediagrams.com/ (I love this one, we use it at work to embed seqdiags in confluence)

Use https://cdn.rawgit.com/ for binary data to provide correct headers.

No native format on Google Drive / Draw

**Comment by gmacario** [comment]
Thanks @lucabelluccini 

Closing issue, @zakkos please reopen if you need additional clarifications
