### ISSUE TITLE
Presentation on Prezi cannot be displayed on UDOObuntu

### ISSUE THREAD

**Issue by gmacario** [kuruho/dansuma#9]
@grigio Could you please explain how to work around such issue?

**Comment by gmacario** [comment]
@grigio Could you please explain how to work around such issue?

**Comment by gmacario** [comment]
Assigned to @grigio as he is now the legitimate owner of the UDOO Quad where the bug may be reproduced

**Comment by grigio** [comment]
You need to install the [User-Agent Switcher](https://chrome.google.com/webstore/detail/user-agent-switcher-for-g/ffhkkpnppgnfaobgihpdblnhmmbodake) Chrome extension and then select ipad as device

**Comment by gmacario** [comment]
Great, thanks!

Closing issue
